"""SDK error types."""

from openagents.interfaces.runtime import ErrorDetails  # noqa: E402  (after .exceptions import)

from .exceptions import (
    AgentNotFoundError,
    BudgetExhausted,
    ConfigError,
    ConfigLoadError,
    ConfigValidationError,
    ExecutionError,
    InvalidInputError,
    LLMConnectionError,
    LLMError,
    LLMRateLimitError,
    LLMResponseError,
    MaxStepsExceeded,
    ModelRetryError,
    OpenAgentsError,
    OutputValidationError,
    PatternError,
    PermanentToolError,
    PluginConfigError,
    PluginError,
    PluginLoadError,
    RetryableToolError,
    SessionError,
    ToolAuthError,
    ToolCancelledError,
    ToolError,
    ToolNotFoundError,
    ToolRateLimitError,
    ToolTimeoutError,
    ToolUnavailableError,
    ToolValidationError,
    UserError,
)

__all__ = [
    "ErrorDetails",
    "AgentNotFoundError",
    "BudgetExhausted",
    "ConfigError",
    "ConfigLoadError",
    "ConfigValidationError",
    "ExecutionError",
    "InvalidInputError",
    "LLMConnectionError",
    "LLMError",
    "LLMRateLimitError",
    "LLMResponseError",
    "MaxStepsExceeded",
    "ModelRetryError",
    "OpenAgentsError",
    "OutputValidationError",
    "PatternError",
    "PermanentToolError",
    "PluginConfigError",
    "PluginError",
    "PluginLoadError",
    "RetryableToolError",
    "SessionError",
    "ToolAuthError",
    "ToolCancelledError",
    "ToolError",
    "ToolNotFoundError",
    "ToolRateLimitError",
    "ToolTimeoutError",
    "ToolUnavailableError",
    "ToolValidationError",
    "UserError",
]
