"""Contracts for plugin development."""

from .capabilities import (
    MEMORY_INJECT,
    MEMORY_RETRIEVE,
    MEMORY_WRITEBACK,
    PATTERN_EXECUTE,
    PATTERN_REACT,
    SKILL_CONTEXT_AUGMENT,
    SKILL_METADATA,
    SKILL_POST_RUN,
    SKILL_PRE_RUN,
    SKILL_SYSTEM_PROMPT,
    SKILL_TOOL_FILTER,
    SKILL_TOOLS,
    TOOL_INVOKE,
)
from .events import (
    EventBusPlugin,
    EVENT_EMIT,
    EVENT_HISTORY,
    EVENT_SUBSCRIBE,
    RUNTIME_SHUTDOWN_COMPLETED,
    RUNTIME_SHUTDOWN_REQUESTED,
    RUNTIME_SHUTDOWN_STARTED,
    RuntimeEvent,
)
from .memory import MemoryPlugin
from .pattern import ExecutionContext, PatternPlugin
from .plugin import BasePlugin
from .runtime import (
    RUNTIME_LIFECYCLE,
    RUNTIME_MANAGE,
    RUNTIME_RUN,
    RunArtifact,
    RunBudget,
    RunRequest,
    RunResult,
    RunUsage,
    RuntimePlugin,
)
from .session import (
    SESSION_ARTIFACTS,
    SESSION_CHECKPOINTS,
    SESSION_MANAGE,
    SESSION_STATE,
    SESSION_TRANSCRIPT,
    SessionArtifact,
    SessionCheckpoint,
    SessionManagerPlugin,
)
from .skill import SkillPlugin
from .tool import (
    ExecutionPolicy,
    PolicyDecision,
    PermanentToolError,
    RetryableToolError,
    ToolError,
    ToolExecutionRequest,
    ToolExecutionResult,
    ToolExecutionSpec,
    ToolExecutor,
    ToolPlugin,
    ToolResult,
)

__all__ = [
    "BasePlugin",
    "ExecutionContext",
    "MemoryPlugin",
    "PatternPlugin",
    "SkillPlugin",
    "ExecutionPolicy",
    "PolicyDecision",
    "ToolPlugin",
    "ToolExecutionSpec",
    "ToolExecutionRequest",
    "ToolExecutionResult",
    "ToolExecutor",
    "ToolError",
    "RetryableToolError",
    "PermanentToolError",
    "ToolResult",
    "RunBudget",
    "RunRequest",
    "RunResult",
    "RunUsage",
    "RunArtifact",
    "RuntimePlugin",
    "SessionArtifact",
    "SessionCheckpoint",
    "SessionManagerPlugin",
    "EventBusPlugin",
    "RuntimeEvent",
    # Capabilities
    "MEMORY_INJECT",
    "MEMORY_RETRIEVE",
    "MEMORY_WRITEBACK",
    "PATTERN_EXECUTE",
    "PATTERN_REACT",
    "SKILL_CONTEXT_AUGMENT",
    "SKILL_SYSTEM_PROMPT",
    "SKILL_TOOLS",
    "SKILL_METADATA",
    "SKILL_TOOL_FILTER",
    "SKILL_PRE_RUN",
    "SKILL_POST_RUN",
    "TOOL_INVOKE",
    "RUNTIME_RUN",
    "RUNTIME_MANAGE",
    "RUNTIME_LIFECYCLE",
    "SESSION_MANAGE",
    "SESSION_STATE",
    "SESSION_TRANSCRIPT",
    "SESSION_ARTIFACTS",
    "SESSION_CHECKPOINTS",
    "EVENT_SUBSCRIBE",
    "EVENT_EMIT",
    "EVENT_HISTORY",
    "RUNTIME_SHUTDOWN_REQUESTED",
    "RUNTIME_SHUTDOWN_STARTED",
    "RUNTIME_SHUTDOWN_COMPLETED",
]
